mysql:
  image: mysql:latest
  restart: always
  environment:
    MYSQL_PORT: ${MYSQL_PORT}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  ports:
  - "${MYSQL_PORT}:${MYSQL_PORT}"
  labels:
    azkaban: db
  volumes:
  - /var/lib/mysql
executor:
  image: puckel/azkaban-executor
  restart: always
  labels:
    azkaban: executor
  links:
  - mysql
webserver:
  image: helk/azkanban-webserver-1.2:ubuntu14.04beta1
  restart: always
  ports:
  - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
  labels:
    azkaban: webserver
  links:
  - executor:azkaban-executor
  - mysql
