mysql:
  image: mysql:latest
  restart: always
  environment:
    MYSQL_PORT: ${MYSQL_PORT}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  ports:
  - "${MYSQL_PORT}:${MYSQL_PORT}"
  labels:
    io.rancher.container.hostname_override: container_name
    azkaban: db
  volumes:
  - /var/lib/mysql
executor:
  image: puckel/azkaban-executor
  restart: always
  labels:
    azkaban: executor
  links:
  - mysql
webserver-config:
  restart: always
  image: helk/azkaban-webserver-conf:beta01
  labels:
    azkaban: webserver-config
  links:
  - mysql
webserver:
  image: helk/azkaban-webserver-beta4
  restart: always
  volumes_from:
  - webserver-config
  ports:
  - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
  labels:
    io.rancher.sidekicks: webserver-config
    azkaban: webserver
  links:
  - executor:azkaban-executor
  - mysql
