mysql:
  image: mysql:latest
  restart: always
  ports:
  - "3306:3306"
  labels:
    azkaban: db
  volumes:
  - /var/lib/mysql
executor:
  image: puckel/azkaban-executor
  restart: always
  labels:
    azkaban: executor
  links:
  - mysql
webserver:
  image: helk/azkaban-webserver:ubuntu14.04beta3
  restart: always
  ports:
  - "8443:8443"
  labels:
    azkaban: webserver
  links:
  - executor:azkaban-executor
  - mysql
