.catalog:
  name: Azkaban
  version: v1
  questions:
  
mysql:
  health_check:
    port: ${MYSQL_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/metrics/snapshot'
    response_timeout: 2000
executor:
  health_check:
    port: 12321
    interval: 5000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: ''
    response_timeout: 3000
webserver:
  health_check:
    port: ${WEBSERVER_PORT}
    interval: 5000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: ''
    response_timeout: 3000
